### ISSUE TITLE
Inore .clazy file when building from source

### ISSUE THREAD

**Issue by rcrdnalor** [MythTV/packaging#100]
Building using ./build-debs.sh master fails on mythtv master due to file .clazy
Note file .clazy does not exist in previous version e.g. fixes/31 

Excerpt from local build log:

```
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building mythtv using existing ./mythtv_32.0~master.20210924.f605061d60.orig.tar.gz
dpkg-source: info: local changes detected, the modified files are:
 mythtv/.clazy
``` 

It is still unclear to me, why the official build recipe on launchpad passes.
On local build, it doesn't.

Patch:
```
diff --git a/deb/debian/source/options b/deb/debian/source/options
index 7863630..cb67cfd 100644
--- a/deb/debian/source/options
+++ b/deb/debian/source/options
@@ -1 +1 @@
-extend-diff-ignore=.github|.dockerignore|.clang-tidy
+extend-diff-ignore=.github|.dockerignore|.clang-tidy|.clazy
```
Attached patch adds .clazy to packaging/deb/debian/source/options 

[ignore_file_clazy_when_building_from_source.zip](https://github.com/MythTV/packaging/files/7229719/ignore_file_clazy_when_building_from_source.zip)

**Comment by superm1** [comment]
What creates this file for you?

**Comment by superm1** [comment]
> Attached patch adds .clazy to packaging/deb/debian/source/options

Can you open a pull request please?
