### ISSUE TITLE
Ubuntu ppa fixes/31 compiles without optimizations

### ISSUE THREAD

**Issue by ulmus-scott** [MythTV/packaging#105]
copied from https://github.com/MythTV/mythtv/issues/406
* **Platform**: Xubuntu 21.04
`Linux htpc 5.11.0-38-generic #42-Ubuntu SMP Fri Sep 24 14:03:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

* **MythTV version**: fixes/31

* **Package version**: mythbuntu ppa

* **Component**: configure

### What steps will reproduce the bug?

look at DWARF debugging info, note no `-O` flag
`readelf -wi <binary> | grep DW_AT_producer`
for example `/usr/lib/debug/.build-id/18/b...` (without the grep, this appears to be libmythtv)
### What is the expected behaviour? 
Optimization flag is set for C++ code is compiled with optimizations: `-O2`, maybe `-O3`, definitely at least `-O1`.

NB: `CFLAGS` includes `-O3`
### What do you see instead?
No `-O` flag is set, so gcc uses its default of `-O0`, no optimizations are performed.

### Additional information
with `./configure --extra-cxxflags=-O1` note `-O1` now in `CXXFLAGS`

**Comment by superm1** [comment]
I seem to recall this was intentional so that we can get debugging symbols.

**Comment by stuarta** [comment]
We should use the profile build in this case, as it both optimises and produces debug symbols

**Comment by superm1** [comment]
I said we do debug, but I meant to say [profile](https://github.com/MythTV/packaging/blob/d8813aed9b4f74ff31f0dce2e56174f5b196ba37/deb/debian/rules#L17).  I forgot there was a differentiation.  So I don't believe there is a packaging action here.

**Comment by ulmus-scott** [comment]
So if I understand correctly, this is WONTFIX since the desire is to use one of the compile types, which should (and now do since v32) set the desired optimization flag(s) in configure?

**Comment by superm1** [comment]
Yeah. If there are optimizations missing they should be added to the profile compile type.

**Comment by ulmus-scott** [comment]
Closing, since this is an issue with configure, not the packaging, and has been fixed in v32, which has been released.
