### ISSUE TITLE
Building on Debian fails due to git:// URLs if user has not set up GitHub credentials

### ISSUE THREAD

**Issue by RaphaelWimmer** [MythTV/packaging#123]
On a clean Debian 11 (i386 in my case), build-debs.sh fails to actually build the v32 packages if no GitHub SSH keys are set up on the build computer because GitHub disabled unauthenticated `git://` access in 2021. The relevant output is:
```
#checkout mythtv
if [ -d .git ]; then \
        git fetch ;\
        git checkout fixes/32 || git checkout master;\
        git pull --rebase; \
        git clean -f -d -X -e Mythbuntu/ -e mythplugins/mythweb/;\
else \
        git clone git://github.com/MythTV/mythtv.git tmp ;\
        mv tmp/.[!.]* tmp/* . ;\
        rm -rf tmp ;\
        git checkout fixes/32 || git checkout master;\
fi
Cloning into 'tmp'...
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
mv: cannot stat 'tmp/.[!.]*': No such file or directory
mv: cannot stat 'tmp/*': No such file or directory
```

Changing all `git://` URLs to `https://` URLs in [mythtv.make](https://github.com/MythTV/packaging/deb/debian/mythtv.make) makes git clone the repo without errors.

**Comment by superm1** [comment]
Would you mind a PR to switch URLs?

**Comment by RaphaelWimmer** [comment]
I'm new to the code base, so I'm not sure whether changing the URLs might have unintended side-effects for other workflows.

**Comment by superm1** [comment]
I don't expect any.  But if we hit something we can always introduce an environment variable for them at that time.
