### ISSUE TITLE
For deb-light are fixes/nn branches relevant

### ISSUE THREAD

**Issue by jfabernathy** [MythTV/packaging#154]
I was noticing on a recent build of deb-light for v33 on a raspberry pi that when I checkout the packaging repository that if I use branch fixes/33 the build fails.  If I just use master, it works.

So the question is, should packaging always stay on master? The file in question was the config.sh which has been edited in mater to accommodate using Raspberry Pi OS 64 bit without the need for a ~/.buildrc file

**Comment by superm1** [comment]
I think the packaging should be brought back too. The packaging branches for regular deb backport fixes as needed.

**Comment by bennettpeter** [comment]
The build should work for all branches. Are you referring to commit f88ada3 that is in master but not fixes/33.

I can cherry-pick that into fixes/33 if that fixes the problem. Let me know.

**Comment by jfabernathy** [comment]
For me having it in fixes/33 would make building mythtv-light have consistent instructions. i.e. git checkout fixes/33 for both  mythtv and packaging

**Comment by jfabernathy** [comment]
The question I have is are there any other changes that have been made to master that should also be in fixes/32 or 33??  My instructions on mythtv forum for v32 did the checkout of fixes/32 for both packaging and mythtv.  When I was trying to update to v33 I found for packaging that if I checked out v33 it failed to build.

**Comment by bennettpeter** [comment]
I have cherry-picked f88ada3 into fixes/33. The deb-light directory is now the same on fixes/33 and master, so that should resolve it.
